export const types = [
    {value:"oil", name: "Oil"},
    {value:"water", name: "Water"},
    {value:"rice", name: "Rice"},
    {value:"jam", name: "Jam"},
    {value:"bean", name: "Bean"},
    {value:"sugar", name: "Sugar"},
    {value:"salt", name: "Salt"},
    {value:"flour", name: "Flour"},
    {value:"spice", name: "Spice"},
    {value:"breads", name: "Breads"},
    {value:"cereals", name: "Cereals"},
    {value:"pasta", name: "Pasta"},
    {value:"sauce", name: "Sauce"},
    {value:"dairy", name: "Dairy"},
    {value:"meat", name: "Meat"},
    {value:"fish", name: "Fish"},
    {value:"vegetables", name: "Vegetables"},
    {value:"fruits", name: "Fruits"},
    {value:"nuts", name: "Nuts"},
    {value:"drinks", name: "Drinks"},
    {value:"alcohol", name: "Alcohol"},
    {value:"snacks", name: "Snacks"},
    {value:"desserts", name: "Desserts"},
    {value:"condiments", name: "Condiments"},
    {value:"other", name: "Other"},
];